### PR TITLE
Improved SVG support

### PR DESCRIPTION
**Pull request by gaa-cifasis**
- Added defs/use support
- Improved transformations

### CODE REVIEW

**Comment by YoshikuniJujo** [comment]
Thank you.
https://hackage.haskell.org/package/yjsvg-0.2.0.0

**Comment by gaa-cifasis** [comment]
You are welcome! Btw, are you interested in keep developing this library?

**Comment by YoshikuniJujo** [comment]
I am happy if you maintain this package.

**Comment by YoshikuniJujo** [comment]
If so, I will add you to collaborator of this repository and hackage.
Please teach me your hackage name.

**Comment by gaa-cifasis** [comment]
I can provide some code from time to time, but i'm not using hackage. Let check how hackage works and i will answer you next week. Ok?

**Comment by YoshikuniJujo** [comment]
OK! Thank you.
I will add you to collaborator of this repository now.

**Comment by gaa-cifasis** [comment]
Thanks!

**Comment by YoshikuniJujo** [comment]
Please add your name to AUTHORS.
Remove (your name) line and write your name.

**Pull request merged**
